In [1]:
import pandas as pd

In [7]:
df1 = pd.read_csv(r'E:\Proyectos\tibber\data\batch_processing_data\batch1.csv')
df2 = pd.read_csv(r'E:\Proyectos\tibber\data\batch_processing_data\batch2.csv')
df3 = pd.read_csv(r'E:\Proyectos\tibber\data\batch_processing_data\batch3.csv')

In [11]:
df1.head(100)

,id,item,price,currency,created_at,updated_at,system_timestamp
0,11111111-1111-1111-1111-111111111111,Pulse,199.99,NOK,2025-03-01T08:00:00+01:00,2025-03-01T08:05:00+01:00,2025-03-01T08:10:00+01:00
1,22222222-2222-2222-2222-222222222222,Smart Pulse,249.50,EUR,2025-03-01T09:15:00+01:00,2025-03-01T09:20:00+01:00,2025-03-01T09:30:00+01:00
2,33333333-3333-3333-3333-333333333333,Tibber Pulse,299.99,USD,2025-03-01T10:00:00+01:00,2025-03-01T10:05:00+01:00,2025-03-01T10:10:00+01:00
3,44444444-4444-4444-4444-444444444444,Energy Monitor,349.99,NOK,2025-03-01T11:00:00+01:00,2025-03-01T11:10:00+01:00,2025-03-01T11:15:00+01:00
4,55555555-5555-5555-5555-555555555555,Smart Sensor,189.95,JPY,2025-03-01T12:00:00+01:00,2025-03-01T12:10:00+01:00,2025-03-01T12:15:00+01:00
5,66666666-6666-6666-6666-666666666666,Pulse Light,129.99,NOK,2025-03-02T08:30:00+01:00,2025-03-02T08:35:00+01:00,2025-03-02T08:40:00+01:00
6,77777777-7777-7777-7777-777777777777,Tibber Energy,399.00,USD,2025-03-02T09:00:00+01:00,2025-03-02T09:05:00+01:00,2025-03-02T09:10:00+01:00
7,88888888-8888-8888-8888-888888888888,Tibber Sensor,219.99,NOK,2025-03-02T10:00:00+01:00,2025-03-02T10:05:00+01:00,2025-03-02T10:10:00+01:00
8,99999999-9999-9999-9999-999999999999,Tibber Charge,279.50,SEK,2025-03-02T11:00:00+01:00,2025-03-02T11:10:00+01:00,2025-03-02T11:15:00+01:00
9,aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa,Pulse Pro,359.99,GBP,2025-03-02T12:00:00+01:00,2025-03-02T12:05:00+01:00,2025-03-02T12:10:00+01:00
10,bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb,Pulse Mini,149.99,NOK,2025-03-03T08:00:00+01:00,2025-03-03T08:05:00+01:00,2025-03-03T08:10:00+01:00
11,cccccccc-cccc-cccc-cccc-cccccccccccc,SmartCharge,409.50,EUR,2025-03-03T09:15:00+01:00,2025-03-03T09:20:00+01:00,2025-03-03T09:30:00+01:00
12,dddddddd-dddd-dddd-dddd-dddddddddddd,Energy Hub,499.99,NOK,2025-03-03T10:00:00+01:00,2025-03-03T10:10:00+01:00,2025-03-03T10:15:00+01:00
13,eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee,Pulse Plus,319.99,USD,2025-03-03T11:00:00+01:00,2025-03-03T11:05:00+01:00,2025-03-03T11:10:00+01:00
14,ffffffff-ffff-ffff-ffff-ffffffffffff,Tibber Home,289.95,NOK,2025-03-03T12:00:00+01:00,2025-03-03T12:05:00+01:00,2025-03-03T12:10:00+01:00
15,12345678-1234-1234-1234-123456789abc,Tibber Connect,269.99,EUR,2025-03-04T08:00:00+01:00,2025-03-04T08:05:00+01:00,2025-03-04T08:10:00+01:00
16,87654321-4321-4321-4321-cba987654321,Pulse X,399.95,NOK,2025-03-04T09:00:00+01:00,2025-03-04T09:05:00+01:00,2025-03-04T09:10:00+01:00
17,abcdefab-cdef-cdef-cdef-abcdefabcdef,SmartPulse X,189.95,JPY,2025-03-04T10:00:00+01:00,2025-03-04T10:05:00+01:00,2025-03-04T10:10:00+01:00
18,fedcbafe-dcba-dcba-dcba-fedcbafedcba,Tibber Elite,429.99,NOK,2025-03-04T11:00:00+01:00,2025-03-04T11:10:00+01:00,2025-03-04T11:15:00+01:00
19,0f0f0f0f-0f0f-0f0f-0f0f-0f0f0f0f0f0f,Pulse Max,359.50,USD,2025-03-04T12:00:00+01:00,2025-03-04T12:05:00+01:00,2025-03-04T12:10:00+01:00

In [12]:
df2.head(100)

,id,item,price,currency,created_at,updated_at,system_timestamp
0,11111111-1111-1111-1111-111111111111,Pulse,209.99,NOK,2025-03-01T08:00:00+01:00,2025-03-05T08:05:00+01:00,2025-03-05T08:10:00+01:00
1,22222222-2222-2222-2222-222222222222,Smart Pulse,259.50,EUR,2025-03-01T09:15:00+01:00,2025-03-05T09:20:00+01:00,2025-03-05T09:30:00+01:00
2,33333333-3333-3333-3333-333333333333,Tibber Pulse,309.99,USD,2025-03-01T10:00:00+01:00,2025-03-05T10:05:00+01:00,2025-03-05T10:10:00+01:00
3,44444444-4444-4444-4444-444444444444,Energy Monitor,359.99,NOK,2025-03-01T11:00:00+01:00,2025-03-05T11:10:00+01:00,2025-03-05T11:15:00+01:00
4,55555555-5555-5555-5555-555555555555,Smart Sensor,199.95,JPY,2025-03-01T12:00:00+01:00,2025-03-05T12:10:00+01:00,2025-03-05T12:15:00+01:00
5,0f0f0f0f-0f0f-0f0f-0f0f-0f0f0f0f0f0f,Pulse Max,99.50,USD,2025-03-03T12:00:00+01:00,2025-03-04T11:05:00+01:00,2025-03-06T12:10:00+01:00

In [13]:
df3.head(100)

,id,item,price,currency,created_at,updated_at,system_timestamp
0,12345678-1234-1234-1234-123456789abc,Tibber Connect,279.99,EUR,2025-03-04T08:00:00+01:00,2025-03-06T08:05:00+01:00,2025-03-06T08:10:00+01:00
1,87654321-4321-4321-4321-cba987654321,Pulse X,409.95,NOK,2025-03-04T09:00:00+01:00,2025-03-06T09:05:00+01:00,2025-03-06T09:10:00+01:00
2,abcdefab-cdef-cdef-cdef-abcdefabcdef,SmartPulse X,199.95,JPY,2025-03-04T10:00:00+01:00,2025-03-06T10:05:00+01:00,2025-03-06T10:10:00+01:00
3,fedcbafe-dcba-dcba-dcba-fedcbafedcba,Tibber Elite,439.99,NOK,2025-03-04T11:00:00+01:00,2025-03-06T11:10:00+01:00,2025-03-06T11:15:00+01:00
4,0f0f0f0f-0f0f-0f0f-0f0f-0f0f0f0f0f0f,Pulse Max,369.50,USD,2025-03-04T12:00:00+01:00,2025-03-06T12:05:00+01:00,2025-03-06T12:10:00+01:00
5,aaaaaaaa-0000-0000-0000-000000000001,Tibber Flex,319.99,NOK,2025-03-06T13:00:00+01:00,2025-03-06T13:05:00+01:00,2025-03-06T13:10:00+01:00
6,aaaaaaaa-0000-0000-0000-000000000002,Pulse Ultra,459.99,EUR,2025-03-06T14:00:00+01:00,2025-03-06T14:05:00+01:00,2025-03-06T14:10:00+01:00
7,aaaaaaaa-0000-0000-0000-000000000003,Smart Energy,389.99,USD,2025-03-06T15:00:00+01:00,2025-03-06T15:05:00+01:00,2025-03-06T15:10:00+01:00
8,aaaaaaaa-0000-0000-0000-000000000004,Tibber Spark,279.99,JPY,2025-03-06T16:00:00+01:00,2025-03-06T16:05:00+01:00,2025-03-06T16:10:00+01:00
9,aaaaaaaa-0000-0000-0000-000000000005,Pulse Plus Pro,499.99,GBP,2025-03-06T17:00:00+01:00,2025-03-06T17:05:00+01:00,2025-03-06T17:10:00+01:00